INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Corriente', 'Ciudad Bolivar', 'Terpel', 150, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Diesel', 'Ciudad Bolivar', 'Terpel', 100, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Corriente', 'Ciudad Bolivar', 'Shell', 200, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Diesel', 'Ciudad Bolivar', 'Shell', 150, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Corriente', 'Ciudad Bolivar', 'Mobil', 250, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Diesel', 'Ciudad Bolivar', 'Mobil', 200, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Diesel', 'Kennedy', 'Terpel', 220, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Corriente', 'Kennedy', 'Shell', 330, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Corriente', 'Kennedy', 'Mobil', 380, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Diesel', 'Kennedy', 'Mobil', 320, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Corriente', 'Suba', 'Terpel', 380, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Diesel', 'Suba', 'Terpel', 320, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Corriente', 'Suba', 'Mobil', 480, 100);
INSERT INTO station (type, zone, franchise, price_difference, quantity) VALUES ('Diesel', 'Suba', 'Mobil', 420, 100);